# Generated by Django 2.2.24 on 2022-02-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='users_id',
        ),
    ]
