# Generated by Django 2.2.24 on 2022-02-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(auto_created=True, default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
