# Generated by Django 2.2.24 on 2022-02-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_administration', '0002_remove_users_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='to_whom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='notes_administration.Users'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='notes_administration.Users'),
        ),
    ]
