# Generated by Django 2.2.24 on 2022-02-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_administration', '0002_auto_20220216_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.AddField(
            model_name='note',
            name='note_id',
            field=models.IntegerField(auto_created=True, default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
