# Generated by Django 2.2.24 on 2022-02-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_administration', '0003_auto_20220202_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='users_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='to_whom',
            field=models.TextField(),
        ),
    ]
