# Generated by Django 2.2.24 on 2022-02-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_administration', '0004_auto_20220207_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
