# Generated by Django 2.2.24 on 2022-02-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_administration', '0005_auto_20220209_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='users_id',
        ),
    ]
